### ISSUE TITLE
CSV Formatter interfers with Swashbuckle

### ISSUE THREAD

**Issue by JohnGalt1717** [WebApiContrib/WebAPIContrib.Core#80] opened 2016-11-26 22:55 UTC
If you add the formatter it will causes the swagger.json file to error and not be returned properly. I couldn't find a parameter in the options that would let me limit what would come back and when it would be applied.

**Comment by damienbod** [comment] 2016-11-27 13:01
Hi @JohnGalt1717 

How do you add the formatter? It should be added in the Startup so that the json formatter remains the default formatter.

If it is just the method in the controller, you need to remove the specific produces csv and use the request header to define the content in the response.

Greetings Damien

**Comment by JohnGalt1717** [comment] 2016-11-27 14:39
It's the first line of ConfigureServices just like the samples:

`            //Add MVC and allow requesting Bson, Plain Text, CSV and jsonp
            services.AddMvc(options =>
            {
                options.AddJsonpOutputFormatter();
            })
            .AddPlainTextFormatters(new PlainTextFormatterOptions
            {
                SupportedMediaTypes = new string[] { "text/plain" }
            })
            //.AddCsvSerializerFormatters(); //Add this back once CSV doesn't interfere with Swagger.
            .AddBsonSerializerFormatters();`

Then Swagger.

I would have expected that the CsvSerializerOptions would have a param to specify the supported media types like the plain text version, because it too causes problems without the line as you see it above.

I'm trying to rely on the user passing the Accepts header with text/csv when all is said and done so that the end consumer is in control of the format they get back.

Thanks!

**Comment by damienbod** [comment] 2016-11-27 20:01
This extension should not cause that problem, just adds a new input and output formatter for text/csv and json remains the default.

https://github.com/WebApiContrib/WebAPIContrib.Core/blob/master/src/WebApiContrib.Core.Formatter.Csv/CsvFormatterMvcBuilderExtensions.cs

The problem is either that swagger uses a default text/csv media header, which I doubt it, or the controller only returns csv.

Can you post your code, or your controller with the problem, and the Startup

Greeting Damien

**Comment by damienbod** [comment] 2017-02-10 11:04
@JohnGalt1717 I'm closing this, let me know if you think this should be reopened.

Greetings Damien

**Comment by sonphnt** [comment] 2017-04-18 13:27
Hi @damienbod 

I am having the problem now. 

`services.AddMvc();

            services.AddMvc().AddJsonOptions(options =>
            {
                options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                options.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.None;
            });

            services.AddMvc().AddCsvSerializerFormatters();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "CMDB API", Version = "v1" });
                //Set the comments path for the swagger json and ui.
                var basePath = PlatformServices.Default.Application.ApplicationBasePath;
                var xmlPath = Path.Combine(basePath, "CMDB.WebAPI.xml");
                c.IncludeXmlComments(xmlPath);
            });`


Got exception when launching swagger
No media types found in 'WebApiContrib.Core.Formatter.Csv.CsvInputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.

**Comment by damienbod** [comment] 2017-04-18 13:59
@JohnGalt1717, @sonphnt  I'll try to reproduce and fix, will get back to you

**Comment by sonphnt** [comment] 2017-04-18 14:27
@damienbod Thanks very much. Hope to hear from you soon.

**Comment by damienbod** [comment] 2017-04-18 18:31
@JohnGalt1717 @sonphnt 
This works for me, could you compare it with your solution?

https://github.com/damienbod/csvSwaggerExample

Greetings Damien

**Comment by sonphnt** [comment] 2017-04-18 19:43
Hi @damienbod 
Your solution has only swagger in startup.cs. Please try to add your CSV framework and run again. I still have the error.

Thanks

**Comment by damienbod** [comment] 2017-04-18 20:00
@sonphnt Have the problem now, thanks

System.InvalidOperationException: No media types found in 'WebApiContrib.Core.Formatter.Csv.CsvInputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.
   at Microsoft.AspNetCore.Mvc.Formatters.InputFormatter.GetSupportedContentTypes(String contentType, Type objectType)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.GetRequestFormats(ControllerActionDescriptor action, IApiRequestMetadataProvider[] requestMetadataAttributes, Type type)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.CreateApiDescription(ControllerActionDescriptor action, String httpMethod, String groupName)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.OnProvidersExecuting(ApiDescriptionProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by sonphnt** [comment] 2017-04-18 20:02
@damienbod Yes, exactly that error. Do you know why?

**Comment by damienbod** [comment] 2017-04-18 20:25
yes, missing SupportedMediaTypes, creating the nuget package now, 10 mins

Thanks for reporting

**Comment by damienbod** [comment] 2017-04-18 20:43
Install-Package WebApiContrib.Core.Formatter.Csv -Version 1.0.3

now works, thanks

**Comment by sonphnt** [comment] 2017-04-19 09:32
@damienbod Thanks. Worked perfectly now.

**Comment by filipw** [comment] 2017-07-03 06:33
This was resolved

**Closed by filipw** 2017-07-03 06:33 UTC
